target: _site

collections:
  - name: posts
    folder: _posts
  - name: books
    folder: _books

categories:
  - features
  - blogging
  - uncategorized

data:
  - _data

datasets:
  - name: calendar
    folder: _datasets/calendar

pageviews:
  - _pages

theme: bootstrap

title: My First Stakx Website

templates:
  redirect: false

highlighter:
  languages:
    bzw: _languages/bzw.json

debug: true

scss:
  style: compressed
  sourcemap: false
