base: /
target: _site

collections:
  - name: posts
    folder: _posts
  - name: books
    folder: _books

data:
  - _data

datasets:
  - name: months
    folder: _datasets/months

pageviews:
  - _pages

theme: bootstrap
debug: true

title: My First Stakx Website