services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  allejo\stakx\DataTransformer\:
    resource: '../DataTransformer/*'

  allejo\stakx\DataTransformer\DataTransformerManager:
    calls:
      - method: addDataTransformers
        arguments: [!tagged stakx.data_transformer]

  allejo\stakx\Manager\:
    resource: '../Manager/*'
    exclude: '../Manager/{Twig}Manager'
    calls:
      - { method: 'setLogger', arguments: ['@logger'] }
      - { method: 'setContainer', arguments: ['@service_container'] }
      - { method: 'compileManager', arguments: [] }

  allejo\stakx\Manager\ThemeManager:
    arguments:
      - null

  allejo\stakx\Configuration:
    calls:
      - { method: 'setLogger', arguments: ['@logger'] }

  allejo\stakx\EventSubscriber\:
    resource: '../EventSubscriber/*'
    tags:
      - { name: 'kernel.event_subscriber' }

  compiler:
    class: allejo\stakx\Compiler
    arguments:
      - '@templating'
    calls:
      - { method: 'setLogger', arguments: ['@logger'] }
      - { method: 'setContainer', arguments: ['@service_container'] }

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  output:
    class: Symfony\Component\Console\Output\ConsoleOutput

  logger:
    class: allejo\stakx\Core\StakxLogger
    arguments:
      - '@output'

  templating:
    class: allejo\stakx\Templating\TwigStakxBridge
    factory: ['allejo\stakx\Templating\TwigStakxBridgeFactory', createTwigEnvironment]
