language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --no-interaction --prefer-dist

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

notifications:
  email: false
  webhooks:
    - http://helit.tech:8093/+sujevo-dev/showSuccessfulBuildMessages=always

addons:
    code_climate:
        repo_token: 322f84178d8f07613755a75b30ea9aaceb7041e6bc1b20eeb3c4726e82c1cc64